slam_toolbox:
  ros__parameters:
    use_sim_time: false
    resolution: 0.03
    max_laser_range: 10.0
    minimum_travel_distance: 0.25
    minimum_travel_heading: 0.17
    transform_publish_period: 0.05
    map_update_interval: 2.0
    use_scan_matching: true
    use_scan_barycenter: true
    laser_max_beams: 720
    loop_closure_threshold: 0.8
    loop_closure_max_distance: 3.0
    optimize_on_loop_closure: true
    use_pose_graph: true
    pose_graph_use_odometry: False # when have odem data make it true
    ceres_solver_threads: 4
    queue_size: 100
    publish_map: true
